#!/bin/sh
# /etc/init.d/beecounter
### BEGIN INIT INFO
# Provides:          beecounter.sh
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: beecounter for HiveControl
# Description:       Counts objects going by the camera in each direction
### END INIT INFO

f_message(){
        echo "[+] $1"
}
 
# Carry out specific functions when asked to by the system
case "$1" in
        start)
                f_message "Starting beecounter"
                /usr/bin/python /home/HiveControl/scripts/beecount/beecounter_svc.py &
                sleep 2
                f_message "beecounter started"
                ;;
        stop)
                f_message "Stopping beecounter…"
                killall beecounter
                f_message "beecounter stopped"
                ;;
        restart)
                f_message "Restarting daemon: beecounter"
                killall beecounter
                /usr/bin/python /home/HiveControl/scripts/beecount/beecounter_svc.py &
                sleep 2
                f_message "Restarted daemon: beecounter"
                ;;
        status)
                pid=`ps -A | grep beecounter | grep -v "grep" | grep -v beecounter. | awk ‘{print $1}’ | head -n 1`
                if [ -n "$pid" ];
                then
                        f_message "beecounter is running with pid ${pid}"
                        f_message "beecounter was started with the following command line"
                        cat /proc/${pid}/cmdline ; echo ""
                else
                        f_message "Could not find beecounter running"
                fi
                ;;
        *)
                f_message "Usage: $0 {start|stop|status|restart}"
                exit 1
                ;;
esac
exit 0
