#!/bin/sh
# /etc/init.d/livestream.sh
### BEGIN INIT INFO
# Provides:          livestream.sh
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mjpg_streamer for webcam
# Description:       Streams USB camera /dev/video0 to http://IP:8080/?action=stream
### END INIT INFO

DEVICE="/dev/video0"
RESOLUTION="640x480"
FPS="15"
PORT="8080"

f_message(){
        echo "[+] $1"
}

case "$1" in
        start)
                f_message "Starting mjpg_streamer on ${DEVICE}"
                /usr/local/bin/mjpg_streamer -b \
                        -i "input_uvc.so -d ${DEVICE} -r ${RESOLUTION} -f ${FPS}" \
                        -o "output_http.so -p ${PORT} -w /usr/local/share/mjpg-streamer/www"
                sleep 2
                f_message "mjpg_streamer started"
                ;;
        stop)
                f_message "Stopping mjpg_streamer…"
                killall mjpg_streamer
                f_message "mjpg_streamer stopped"
                ;;
        restart)
                f_message "Restarting daemon: mjpg_streamer"
                killall mjpg_streamer
                /usr/local/bin/mjpg_streamer -b \
                        -i "input_uvc.so -d ${DEVICE} -r ${RESOLUTION} -f ${FPS}" \
                        -o "output_http.so -p ${PORT} -w /usr/local/share/mjpg-streamer/www"
                sleep 2
                f_message "Restarted daemon: mjpg_streamer"
                ;;
        status)
                pid=`ps -A | grep mjpg_streamer | grep -v "grep" | grep -v mjpg_streamer. | awk ‘{print $1}’ | head -n 1`
                if [ -n "$pid" ];
                then
                        f_message "mjpg_streamer is running with pid ${pid}"
                        f_message "mjpg_streamer was started with the following command line"
                        cat /proc/${pid}/cmdline ; echo ""
                else
                        f_message "Could not find mjpg_streamer running"
                fi
                ;;
        *)
                f_message "Usage: $0 {start|stop|status|restart}"
                exit 1
                ;;
esac
exit 0
