/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_AdvancedServoPhidget */

#ifndef _Included_com_phidgets_AdvancedServoPhidget
#define _Included_com_phidgets_AdvancedServoPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_INFO
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_VERBOSE 6L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_NOTHING
#define com_phidgets_AdvancedServoPhidget_PHIDID_NOTHING 1L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ACCELEROMETER_3AXIS
#define com_phidgets_AdvancedServoPhidget_PHIDID_ACCELEROMETER_3AXIS 126L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ADVANCEDSERVO_1MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_ADVANCEDSERVO_1MOTOR 130L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ADVANCEDSERVO_8MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_ADVANCEDSERVO_8MOTOR 58L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ANALOG_4OUTPUT
#define com_phidgets_AdvancedServoPhidget_PHIDID_ANALOG_4OUTPUT 55L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR 123L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_BRIDGE_4INPUT
#define com_phidgets_AdvancedServoPhidget_PHIDID_BRIDGE_4INPUT 59L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ENCODER_1ENCODER_1INPUT
#define com_phidgets_AdvancedServoPhidget_PHIDID_ENCODER_1ENCODER_1INPUT 75L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ENCODER_HS_1ENCODER
#define com_phidgets_AdvancedServoPhidget_PHIDID_ENCODER_HS_1ENCODER 128L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT
#define com_phidgets_AdvancedServoPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT 79L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT
#define com_phidgets_AdvancedServoPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT 53L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_GPS
#define com_phidgets_AdvancedServoPhidget_PHIDID_GPS 121L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_0_4
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_0_4 64L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_0_8
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_0_8 129L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_16_16
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_16_16 68L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_2_2_2
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_2_2_2 54L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_8_8_8
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_8_8_8 69L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD 125L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_IR
#define com_phidgets_AdvancedServoPhidget_PHIDID_IR 77L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_LED_64_ADV
#define com_phidgets_AdvancedServoPhidget_PHIDID_LED_64_ADV 76L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_LINEAR_TOUCH
#define com_phidgets_AdvancedServoPhidget_PHIDID_LINEAR_TOUCH 118L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_MOTORCONTROL_1MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_MOTORCONTROL_1MOTOR 62L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR 89L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_RFID_2OUTPUT
#define com_phidgets_AdvancedServoPhidget_PHIDID_RFID_2OUTPUT 49L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE
#define com_phidgets_AdvancedServoPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE 52L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ROTARY_TOUCH
#define com_phidgets_AdvancedServoPhidget_PHIDID_ROTARY_TOUCH 119L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_SPATIAL_ACCEL_3AXIS
#define com_phidgets_AdvancedServoPhidget_PHIDID_SPATIAL_ACCEL_3AXIS 127L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS
#define com_phidgets_AdvancedServoPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS 51L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEMPERATURESENSOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEMPERATURESENSOR 112L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEMPERATURESENSOR_4
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEMPERATURESENSOR_4 50L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEMPERATURESENSOR_IR
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEMPERATURESENSOR_IR 60L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8 381L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_ADAPTER
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_ADAPTER 61L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR 122L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_ACCELEROMETER_2AXIS
#define com_phidgets_AdvancedServoPhidget_PHIDID_ACCELEROMETER_2AXIS 113L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD 83L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_4_8_8
#define com_phidgets_AdvancedServoPhidget_PHIDID_INTERFACEKIT_4_8_8 4L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_LED_64
#define com_phidgets_AdvancedServoPhidget_PHIDID_LED_64 74L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT
#define com_phidgets_AdvancedServoPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT 88L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_PHSENSOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_PHSENSOR 116L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_RFID
#define com_phidgets_AdvancedServoPhidget_PHIDID_RFID 48L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_1MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_1MOTOR 57L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_1MOTOR_OLD
#define com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_1MOTOR_OLD 2L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_4MOTOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_4MOTOR 56L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_4MOTOR_OLD
#define com_phidgets_AdvancedServoPhidget_PHIDID_SERVO_4MOTOR_OLD 3L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_2x20
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_2x20 82L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8 339L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLED_1x8
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLED_1x8 73L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLED_4x8
#define com_phidgets_AdvancedServoPhidget_PHIDID_TEXTLED_4x8 72L
#undef com_phidgets_AdvancedServoPhidget_PHIDID_WEIGHTSENSOR
#define com_phidgets_AdvancedServoPhidget_PHIDID_WEIGHTSENSOR 114L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_NOTHING
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_NOTHING 1L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_ACCELEROMETER
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_ACCELEROMETER 2L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_ADVANCEDSERVO
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_ADVANCEDSERVO 3L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_ANALOG
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_ANALOG 22L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_BRIDGE
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_BRIDGE 23L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_ENCODER
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_ENCODER 4L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_FREQUENCYCOUNTER
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_FREQUENCYCOUNTER 21L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_GPS
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_GPS 5L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_INTERFACEKIT
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_INTERFACEKIT 7L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_LED
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_LED 8L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_MOTORCONTROL
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_MOTORCONTROL 9L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_PHSENSOR
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_PHSENSOR 10L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_RFID
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_RFID 11L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_SERVO
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_SERVO 12L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_STEPPER
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_STEPPER 13L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_TEMPERATURESENSOR
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_TEMPERATURESENSOR 14L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_TEXTLCD
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_TEXTLCD 15L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_TEXTLED
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_TEXTLED 16L
#undef com_phidgets_AdvancedServoPhidget_PHIDCLASS_WEIGHTSENSOR
#define com_phidgets_AdvancedServoPhidget_PHIDCLASS_WEIGHTSENSOR 17L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_DEFAULT
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_DEFAULT 1L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_RAW_us_MODE
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_RAW_us_MODE 2L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS322HD
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS322HD 3L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS5245MG
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS5245MG 4L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_805BB
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_805BB 5L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS422
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS422 6L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_TOWERPRO_MG90
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_TOWERPRO_MG90 7L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HSR1425CR
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HSR1425CR 8L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS785HB
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS785HB 9L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS485HB
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS485HB 10L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS645MG
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_HS645MG 11L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_815BB
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_HITEC_815BB 12L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_30_50_06_R
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_30_50_06_R 13L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_50_100_06_R
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_50_100_06_R 14L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_50_210_06_R
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_50_210_06_R 15L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_100_50_06_R
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_100_50_06_R 16L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_100_100_06_R
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_FIRGELLI_L12_100_100_06_R 17L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S2313M
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S2313M 18L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S3317M
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S3317M 19L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S3317SR
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S3317SR 20L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4303R
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4303R 21L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4315M
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4315M 22L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4315R
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4315R 23L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4505B
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_SPRINGRC_SM_S4505B 24L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_USER_DEFINED
#define com_phidgets_AdvancedServoPhidget_PHIDGET_SERVO_USER_DEFINED 25L
/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_AdvancedServoPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getMotorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_AdvancedServoPhidget_getMotorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getAccelerationMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getAccelerationMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getAccelerationMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getAccelerationMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocityMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocityMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocityMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocityMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getPositionMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getPositionMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setPositionMax
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setPositionMax
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getPositionMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getPositionMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setPositionMin
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setPositionMin
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getAcceleration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getAcceleration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setAcceleration
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setAcceleration
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocityLimit
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocityLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setVelocityLimit
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setVelocityLimit
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocity
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getPosition
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setPosition
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setPosition
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getEngaged
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_AdvancedServoPhidget_getEngaged
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setEngaged
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setEngaged
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getSpeedRampingOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_AdvancedServoPhidget_getSpeedRampingOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setSpeedRampingOn
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setSpeedRampingOn
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getStopped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_AdvancedServoPhidget_getStopped
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getServoType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_AdvancedServoPhidget_getServoType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setServoType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setServoType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setServoParameters
 * Signature: (IDDDD)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setServoParameters
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    enableServoPositionChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_enableServoPositionChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    enableServoVelocityChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_enableServoVelocityChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    enableCurrentChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_enableCurrentChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
