/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_BridgePhidget */

#ifndef _Included_com_phidgets_BridgePhidget
#define _Included_com_phidgets_BridgePhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_BridgePhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_BridgePhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_BridgePhidget_PHIDGET_LOG_ERROR
#define com_phidgets_BridgePhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_BridgePhidget_PHIDGET_LOG_WARNING
#define com_phidgets_BridgePhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_BridgePhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_BridgePhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_BridgePhidget_PHIDGET_LOG_INFO
#define com_phidgets_BridgePhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_BridgePhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_BridgePhidget_PHIDGET_LOG_VERBOSE 6L
#undef com_phidgets_BridgePhidget_PHIDID_NOTHING
#define com_phidgets_BridgePhidget_PHIDID_NOTHING 1L
#undef com_phidgets_BridgePhidget_PHIDID_ACCELEROMETER_3AXIS
#define com_phidgets_BridgePhidget_PHIDID_ACCELEROMETER_3AXIS 126L
#undef com_phidgets_BridgePhidget_PHIDID_ADVANCEDSERVO_1MOTOR
#define com_phidgets_BridgePhidget_PHIDID_ADVANCEDSERVO_1MOTOR 130L
#undef com_phidgets_BridgePhidget_PHIDID_ADVANCEDSERVO_8MOTOR
#define com_phidgets_BridgePhidget_PHIDID_ADVANCEDSERVO_8MOTOR 58L
#undef com_phidgets_BridgePhidget_PHIDID_ANALOG_4OUTPUT
#define com_phidgets_BridgePhidget_PHIDID_ANALOG_4OUTPUT 55L
#undef com_phidgets_BridgePhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR
#define com_phidgets_BridgePhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR 123L
#undef com_phidgets_BridgePhidget_PHIDID_BRIDGE_4INPUT
#define com_phidgets_BridgePhidget_PHIDID_BRIDGE_4INPUT 59L
#undef com_phidgets_BridgePhidget_PHIDID_ENCODER_1ENCODER_1INPUT
#define com_phidgets_BridgePhidget_PHIDID_ENCODER_1ENCODER_1INPUT 75L
#undef com_phidgets_BridgePhidget_PHIDID_ENCODER_HS_1ENCODER
#define com_phidgets_BridgePhidget_PHIDID_ENCODER_HS_1ENCODER 128L
#undef com_phidgets_BridgePhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT
#define com_phidgets_BridgePhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT 79L
#undef com_phidgets_BridgePhidget_PHIDID_FREQUENCYCOUNTER_2INPUT
#define com_phidgets_BridgePhidget_PHIDID_FREQUENCYCOUNTER_2INPUT 53L
#undef com_phidgets_BridgePhidget_PHIDID_GPS
#define com_phidgets_BridgePhidget_PHIDID_GPS 121L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_0_4
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_0_4 64L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_0_8
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_0_8 129L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_16_16
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_16_16 68L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_2_2_2
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_2_2_2 54L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_8_8_8
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_8_8_8 69L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD 125L
#undef com_phidgets_BridgePhidget_PHIDID_IR
#define com_phidgets_BridgePhidget_PHIDID_IR 77L
#undef com_phidgets_BridgePhidget_PHIDID_LED_64_ADV
#define com_phidgets_BridgePhidget_PHIDID_LED_64_ADV 76L
#undef com_phidgets_BridgePhidget_PHIDID_LINEAR_TOUCH
#define com_phidgets_BridgePhidget_PHIDID_LINEAR_TOUCH 118L
#undef com_phidgets_BridgePhidget_PHIDID_MOTORCONTROL_1MOTOR
#define com_phidgets_BridgePhidget_PHIDID_MOTORCONTROL_1MOTOR 62L
#undef com_phidgets_BridgePhidget_PHIDID_MOTORCONTROL_HC_2MOTOR
#define com_phidgets_BridgePhidget_PHIDID_MOTORCONTROL_HC_2MOTOR 89L
#undef com_phidgets_BridgePhidget_PHIDID_RFID_2OUTPUT
#define com_phidgets_BridgePhidget_PHIDID_RFID_2OUTPUT 49L
#undef com_phidgets_BridgePhidget_PHIDID_RFID_2OUTPUT_READ_WRITE
#define com_phidgets_BridgePhidget_PHIDID_RFID_2OUTPUT_READ_WRITE 52L
#undef com_phidgets_BridgePhidget_PHIDID_ROTARY_TOUCH
#define com_phidgets_BridgePhidget_PHIDID_ROTARY_TOUCH 119L
#undef com_phidgets_BridgePhidget_PHIDID_SPATIAL_ACCEL_3AXIS
#define com_phidgets_BridgePhidget_PHIDID_SPATIAL_ACCEL_3AXIS 127L
#undef com_phidgets_BridgePhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS
#define com_phidgets_BridgePhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS 51L
#undef com_phidgets_BridgePhidget_PHIDID_TEMPERATURESENSOR
#define com_phidgets_BridgePhidget_PHIDID_TEMPERATURESENSOR 112L
#undef com_phidgets_BridgePhidget_PHIDID_TEMPERATURESENSOR_4
#define com_phidgets_BridgePhidget_PHIDID_TEMPERATURESENSOR_4 50L
#undef com_phidgets_BridgePhidget_PHIDID_TEMPERATURESENSOR_IR
#define com_phidgets_BridgePhidget_PHIDID_TEMPERATURESENSOR_IR 60L
#undef com_phidgets_BridgePhidget_PHIDID_TEXTLCD_2x20_w_8_8_8
#define com_phidgets_BridgePhidget_PHIDID_TEXTLCD_2x20_w_8_8_8 381L
#undef com_phidgets_BridgePhidget_PHIDID_TEXTLCD_ADAPTER
#define com_phidgets_BridgePhidget_PHIDID_TEXTLCD_ADAPTER 61L
#undef com_phidgets_BridgePhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR
#define com_phidgets_BridgePhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR 122L
#undef com_phidgets_BridgePhidget_PHIDID_ACCELEROMETER_2AXIS
#define com_phidgets_BridgePhidget_PHIDID_ACCELEROMETER_2AXIS 113L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD 83L
#undef com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_4_8_8
#define com_phidgets_BridgePhidget_PHIDID_INTERFACEKIT_4_8_8 4L
#undef com_phidgets_BridgePhidget_PHIDID_LED_64
#define com_phidgets_BridgePhidget_PHIDID_LED_64 74L
#undef com_phidgets_BridgePhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT
#define com_phidgets_BridgePhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT 88L
#undef com_phidgets_BridgePhidget_PHIDID_PHSENSOR
#define com_phidgets_BridgePhidget_PHIDID_PHSENSOR 116L
#undef com_phidgets_BridgePhidget_PHIDID_RFID
#define com_phidgets_BridgePhidget_PHIDID_RFID 48L
#undef com_phidgets_BridgePhidget_PHIDID_SERVO_1MOTOR
#define com_phidgets_BridgePhidget_PHIDID_SERVO_1MOTOR 57L
#undef com_phidgets_BridgePhidget_PHIDID_SERVO_1MOTOR_OLD
#define com_phidgets_BridgePhidget_PHIDID_SERVO_1MOTOR_OLD 2L
#undef com_phidgets_BridgePhidget_PHIDID_SERVO_4MOTOR
#define com_phidgets_BridgePhidget_PHIDID_SERVO_4MOTOR 56L
#undef com_phidgets_BridgePhidget_PHIDID_SERVO_4MOTOR_OLD
#define com_phidgets_BridgePhidget_PHIDID_SERVO_4MOTOR_OLD 3L
#undef com_phidgets_BridgePhidget_PHIDID_TEXTLCD_2x20
#define com_phidgets_BridgePhidget_PHIDID_TEXTLCD_2x20 82L
#undef com_phidgets_BridgePhidget_PHIDID_TEXTLCD_2x20_w_0_8_8
#define com_phidgets_BridgePhidget_PHIDID_TEXTLCD_2x20_w_0_8_8 339L
#undef com_phidgets_BridgePhidget_PHIDID_TEXTLED_1x8
#define com_phidgets_BridgePhidget_PHIDID_TEXTLED_1x8 73L
#undef com_phidgets_BridgePhidget_PHIDID_TEXTLED_4x8
#define com_phidgets_BridgePhidget_PHIDID_TEXTLED_4x8 72L
#undef com_phidgets_BridgePhidget_PHIDID_WEIGHTSENSOR
#define com_phidgets_BridgePhidget_PHIDID_WEIGHTSENSOR 114L
#undef com_phidgets_BridgePhidget_PHIDCLASS_NOTHING
#define com_phidgets_BridgePhidget_PHIDCLASS_NOTHING 1L
#undef com_phidgets_BridgePhidget_PHIDCLASS_ACCELEROMETER
#define com_phidgets_BridgePhidget_PHIDCLASS_ACCELEROMETER 2L
#undef com_phidgets_BridgePhidget_PHIDCLASS_ADVANCEDSERVO
#define com_phidgets_BridgePhidget_PHIDCLASS_ADVANCEDSERVO 3L
#undef com_phidgets_BridgePhidget_PHIDCLASS_ANALOG
#define com_phidgets_BridgePhidget_PHIDCLASS_ANALOG 22L
#undef com_phidgets_BridgePhidget_PHIDCLASS_BRIDGE
#define com_phidgets_BridgePhidget_PHIDCLASS_BRIDGE 23L
#undef com_phidgets_BridgePhidget_PHIDCLASS_ENCODER
#define com_phidgets_BridgePhidget_PHIDCLASS_ENCODER 4L
#undef com_phidgets_BridgePhidget_PHIDCLASS_FREQUENCYCOUNTER
#define com_phidgets_BridgePhidget_PHIDCLASS_FREQUENCYCOUNTER 21L
#undef com_phidgets_BridgePhidget_PHIDCLASS_GPS
#define com_phidgets_BridgePhidget_PHIDCLASS_GPS 5L
#undef com_phidgets_BridgePhidget_PHIDCLASS_INTERFACEKIT
#define com_phidgets_BridgePhidget_PHIDCLASS_INTERFACEKIT 7L
#undef com_phidgets_BridgePhidget_PHIDCLASS_LED
#define com_phidgets_BridgePhidget_PHIDCLASS_LED 8L
#undef com_phidgets_BridgePhidget_PHIDCLASS_MOTORCONTROL
#define com_phidgets_BridgePhidget_PHIDCLASS_MOTORCONTROL 9L
#undef com_phidgets_BridgePhidget_PHIDCLASS_PHSENSOR
#define com_phidgets_BridgePhidget_PHIDCLASS_PHSENSOR 10L
#undef com_phidgets_BridgePhidget_PHIDCLASS_RFID
#define com_phidgets_BridgePhidget_PHIDCLASS_RFID 11L
#undef com_phidgets_BridgePhidget_PHIDCLASS_SERVO
#define com_phidgets_BridgePhidget_PHIDCLASS_SERVO 12L
#undef com_phidgets_BridgePhidget_PHIDCLASS_STEPPER
#define com_phidgets_BridgePhidget_PHIDCLASS_STEPPER 13L
#undef com_phidgets_BridgePhidget_PHIDCLASS_TEMPERATURESENSOR
#define com_phidgets_BridgePhidget_PHIDCLASS_TEMPERATURESENSOR 14L
#undef com_phidgets_BridgePhidget_PHIDCLASS_TEXTLCD
#define com_phidgets_BridgePhidget_PHIDCLASS_TEXTLCD 15L
#undef com_phidgets_BridgePhidget_PHIDCLASS_TEXTLED
#define com_phidgets_BridgePhidget_PHIDCLASS_TEXTLED 16L
#undef com_phidgets_BridgePhidget_PHIDCLASS_WEIGHTSENSOR
#define com_phidgets_BridgePhidget_PHIDCLASS_WEIGHTSENSOR 17L
#undef com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_1
#define com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_1 1L
#undef com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_8
#define com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_8 2L
#undef com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_16
#define com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_16 3L
#undef com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_32
#define com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_32 4L
#undef com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_64
#define com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_64 5L
#undef com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_128
#define com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_128 6L
#undef com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_UNKNOWN
#define com_phidgets_BridgePhidget_PHIDGET_BRIDGE_GAIN_UNKNOWN 7L
/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_BridgePhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getInputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_BridgePhidget_getInputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getBridgeValue
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_BridgePhidget_getBridgeValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getBridgeMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_BridgePhidget_getBridgeMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getBridgeMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_BridgePhidget_getBridgeMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_BridgePhidget_getEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    setEnabled
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_BridgePhidget_setEnabled
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getGain
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_BridgePhidget_getGain
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    setGain
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_BridgePhidget_setGain
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getDataRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_BridgePhidget_getDataRate
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    setDataRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_BridgePhidget_setDataRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getDataRateMin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_BridgePhidget_getDataRateMin
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    getDataRateMax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_BridgePhidget_getDataRateMax
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_BridgePhidget
 * Method:    enableBridgeDataEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_BridgePhidget_enableBridgeDataEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
