/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_DictionaryKeyListener */

#ifndef _Included_com_phidgets_DictionaryKeyListener
#define _Included_com_phidgets_DictionaryKeyListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phidgets_DictionaryKeyListener
 * Method:    enableDictionaryKeyEvents
 * Signature: (ZLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_DictionaryKeyListener_enableDictionaryKeyEvents
  (JNIEnv *, jobject, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
