/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_MotorControlPhidget */

#ifndef _Included_com_phidgets_MotorControlPhidget
#define _Included_com_phidgets_MotorControlPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_INFO
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_VERBOSE 6L
#undef com_phidgets_MotorControlPhidget_PHIDID_NOTHING
#define com_phidgets_MotorControlPhidget_PHIDID_NOTHING 1L
#undef com_phidgets_MotorControlPhidget_PHIDID_ACCELEROMETER_3AXIS
#define com_phidgets_MotorControlPhidget_PHIDID_ACCELEROMETER_3AXIS 126L
#undef com_phidgets_MotorControlPhidget_PHIDID_ADVANCEDSERVO_1MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_ADVANCEDSERVO_1MOTOR 130L
#undef com_phidgets_MotorControlPhidget_PHIDID_ADVANCEDSERVO_8MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_ADVANCEDSERVO_8MOTOR 58L
#undef com_phidgets_MotorControlPhidget_PHIDID_ANALOG_4OUTPUT
#define com_phidgets_MotorControlPhidget_PHIDID_ANALOG_4OUTPUT 55L
#undef com_phidgets_MotorControlPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR 123L
#undef com_phidgets_MotorControlPhidget_PHIDID_BRIDGE_4INPUT
#define com_phidgets_MotorControlPhidget_PHIDID_BRIDGE_4INPUT 59L
#undef com_phidgets_MotorControlPhidget_PHIDID_ENCODER_1ENCODER_1INPUT
#define com_phidgets_MotorControlPhidget_PHIDID_ENCODER_1ENCODER_1INPUT 75L
#undef com_phidgets_MotorControlPhidget_PHIDID_ENCODER_HS_1ENCODER
#define com_phidgets_MotorControlPhidget_PHIDID_ENCODER_HS_1ENCODER 128L
#undef com_phidgets_MotorControlPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT
#define com_phidgets_MotorControlPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT 79L
#undef com_phidgets_MotorControlPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT
#define com_phidgets_MotorControlPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT 53L
#undef com_phidgets_MotorControlPhidget_PHIDID_GPS
#define com_phidgets_MotorControlPhidget_PHIDID_GPS 121L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_0_4
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_0_4 64L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_0_8
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_0_8 129L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_16_16
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_16_16 68L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_2_2_2
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_2_2_2 54L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_8_8_8
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_8_8_8 69L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD 125L
#undef com_phidgets_MotorControlPhidget_PHIDID_IR
#define com_phidgets_MotorControlPhidget_PHIDID_IR 77L
#undef com_phidgets_MotorControlPhidget_PHIDID_LED_64_ADV
#define com_phidgets_MotorControlPhidget_PHIDID_LED_64_ADV 76L
#undef com_phidgets_MotorControlPhidget_PHIDID_LINEAR_TOUCH
#define com_phidgets_MotorControlPhidget_PHIDID_LINEAR_TOUCH 118L
#undef com_phidgets_MotorControlPhidget_PHIDID_MOTORCONTROL_1MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_MOTORCONTROL_1MOTOR 62L
#undef com_phidgets_MotorControlPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR 89L
#undef com_phidgets_MotorControlPhidget_PHIDID_RFID_2OUTPUT
#define com_phidgets_MotorControlPhidget_PHIDID_RFID_2OUTPUT 49L
#undef com_phidgets_MotorControlPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE
#define com_phidgets_MotorControlPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE 52L
#undef com_phidgets_MotorControlPhidget_PHIDID_ROTARY_TOUCH
#define com_phidgets_MotorControlPhidget_PHIDID_ROTARY_TOUCH 119L
#undef com_phidgets_MotorControlPhidget_PHIDID_SPATIAL_ACCEL_3AXIS
#define com_phidgets_MotorControlPhidget_PHIDID_SPATIAL_ACCEL_3AXIS 127L
#undef com_phidgets_MotorControlPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS
#define com_phidgets_MotorControlPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS 51L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEMPERATURESENSOR
#define com_phidgets_MotorControlPhidget_PHIDID_TEMPERATURESENSOR 112L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEMPERATURESENSOR_4
#define com_phidgets_MotorControlPhidget_PHIDID_TEMPERATURESENSOR_4 50L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEMPERATURESENSOR_IR
#define com_phidgets_MotorControlPhidget_PHIDID_TEMPERATURESENSOR_IR 60L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8
#define com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8 381L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_ADAPTER
#define com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_ADAPTER 61L
#undef com_phidgets_MotorControlPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR 122L
#undef com_phidgets_MotorControlPhidget_PHIDID_ACCELEROMETER_2AXIS
#define com_phidgets_MotorControlPhidget_PHIDID_ACCELEROMETER_2AXIS 113L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD 83L
#undef com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_4_8_8
#define com_phidgets_MotorControlPhidget_PHIDID_INTERFACEKIT_4_8_8 4L
#undef com_phidgets_MotorControlPhidget_PHIDID_LED_64
#define com_phidgets_MotorControlPhidget_PHIDID_LED_64 74L
#undef com_phidgets_MotorControlPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT
#define com_phidgets_MotorControlPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT 88L
#undef com_phidgets_MotorControlPhidget_PHIDID_PHSENSOR
#define com_phidgets_MotorControlPhidget_PHIDID_PHSENSOR 116L
#undef com_phidgets_MotorControlPhidget_PHIDID_RFID
#define com_phidgets_MotorControlPhidget_PHIDID_RFID 48L
#undef com_phidgets_MotorControlPhidget_PHIDID_SERVO_1MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_SERVO_1MOTOR 57L
#undef com_phidgets_MotorControlPhidget_PHIDID_SERVO_1MOTOR_OLD
#define com_phidgets_MotorControlPhidget_PHIDID_SERVO_1MOTOR_OLD 2L
#undef com_phidgets_MotorControlPhidget_PHIDID_SERVO_4MOTOR
#define com_phidgets_MotorControlPhidget_PHIDID_SERVO_4MOTOR 56L
#undef com_phidgets_MotorControlPhidget_PHIDID_SERVO_4MOTOR_OLD
#define com_phidgets_MotorControlPhidget_PHIDID_SERVO_4MOTOR_OLD 3L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_2x20
#define com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_2x20 82L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8
#define com_phidgets_MotorControlPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8 339L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEXTLED_1x8
#define com_phidgets_MotorControlPhidget_PHIDID_TEXTLED_1x8 73L
#undef com_phidgets_MotorControlPhidget_PHIDID_TEXTLED_4x8
#define com_phidgets_MotorControlPhidget_PHIDID_TEXTLED_4x8 72L
#undef com_phidgets_MotorControlPhidget_PHIDID_WEIGHTSENSOR
#define com_phidgets_MotorControlPhidget_PHIDID_WEIGHTSENSOR 114L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_NOTHING
#define com_phidgets_MotorControlPhidget_PHIDCLASS_NOTHING 1L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_ACCELEROMETER
#define com_phidgets_MotorControlPhidget_PHIDCLASS_ACCELEROMETER 2L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_ADVANCEDSERVO
#define com_phidgets_MotorControlPhidget_PHIDCLASS_ADVANCEDSERVO 3L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_ANALOG
#define com_phidgets_MotorControlPhidget_PHIDCLASS_ANALOG 22L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_BRIDGE
#define com_phidgets_MotorControlPhidget_PHIDCLASS_BRIDGE 23L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_ENCODER
#define com_phidgets_MotorControlPhidget_PHIDCLASS_ENCODER 4L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_FREQUENCYCOUNTER
#define com_phidgets_MotorControlPhidget_PHIDCLASS_FREQUENCYCOUNTER 21L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_GPS
#define com_phidgets_MotorControlPhidget_PHIDCLASS_GPS 5L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_INTERFACEKIT
#define com_phidgets_MotorControlPhidget_PHIDCLASS_INTERFACEKIT 7L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_LED
#define com_phidgets_MotorControlPhidget_PHIDCLASS_LED 8L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_MOTORCONTROL
#define com_phidgets_MotorControlPhidget_PHIDCLASS_MOTORCONTROL 9L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_PHSENSOR
#define com_phidgets_MotorControlPhidget_PHIDCLASS_PHSENSOR 10L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_RFID
#define com_phidgets_MotorControlPhidget_PHIDCLASS_RFID 11L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_SERVO
#define com_phidgets_MotorControlPhidget_PHIDCLASS_SERVO 12L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_STEPPER
#define com_phidgets_MotorControlPhidget_PHIDCLASS_STEPPER 13L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_TEMPERATURESENSOR
#define com_phidgets_MotorControlPhidget_PHIDCLASS_TEMPERATURESENSOR 14L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_TEXTLCD
#define com_phidgets_MotorControlPhidget_PHIDCLASS_TEXTLCD 15L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_TEXTLED
#define com_phidgets_MotorControlPhidget_PHIDCLASS_TEXTLED 16L
#undef com_phidgets_MotorControlPhidget_PHIDCLASS_WEIGHTSENSOR
#define com_phidgets_MotorControlPhidget_PHIDCLASS_WEIGHTSENSOR 17L
/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_MotorControlPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getMotorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getMotorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getInputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getInputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getEncoderCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getEncoderCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getSensorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getSensorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getInputState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_MotorControlPhidget_getInputState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getEncoderPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getEncoderPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setEncoderPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setEncoderPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getSensorValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getSensorValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getSensorRawValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getSensorRawValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getRatiometric
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_MotorControlPhidget_getRatiometric
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setRatiometric
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setRatiometric
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getAcceleration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getAcceleration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setAcceleration
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setAcceleration
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getAccelerationMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getAccelerationMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getAccelerationMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getAccelerationMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getVelocity
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getVelocity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getSpeed
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setVelocity
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setVelocity
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setSpeed
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setSpeed
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getBackEMFSensingState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_MotorControlPhidget_getBackEMFSensingState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setBackEMFSensingState
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setBackEMFSensingState
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getBackEMF
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getBackEMF
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getSupplyVoltage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getSupplyVoltage
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getBraking
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getBraking
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setBraking
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setBraking
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableMotorVelocityChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableMotorVelocityChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableCurrentChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableCurrentChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableCurrentUpdateEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableCurrentUpdateEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableInputChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableInputChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableEncoderPositionChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableEncoderPositionChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableEncoderPositionUpdateEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableEncoderPositionUpdateEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableBackEMFUpdateEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableBackEMFUpdateEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableSensorUpdateEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableSensorUpdateEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
