/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_StepperPhidget */

#ifndef _Included_com_phidgets_StepperPhidget
#define _Included_com_phidgets_StepperPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_StepperPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_StepperPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_StepperPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_StepperPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_INFO
#define com_phidgets_StepperPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_StepperPhidget_PHIDGET_LOG_VERBOSE 6L
#undef com_phidgets_StepperPhidget_PHIDID_NOTHING
#define com_phidgets_StepperPhidget_PHIDID_NOTHING 1L
#undef com_phidgets_StepperPhidget_PHIDID_ACCELEROMETER_3AXIS
#define com_phidgets_StepperPhidget_PHIDID_ACCELEROMETER_3AXIS 126L
#undef com_phidgets_StepperPhidget_PHIDID_ADVANCEDSERVO_1MOTOR
#define com_phidgets_StepperPhidget_PHIDID_ADVANCEDSERVO_1MOTOR 130L
#undef com_phidgets_StepperPhidget_PHIDID_ADVANCEDSERVO_8MOTOR
#define com_phidgets_StepperPhidget_PHIDID_ADVANCEDSERVO_8MOTOR 58L
#undef com_phidgets_StepperPhidget_PHIDID_ANALOG_4OUTPUT
#define com_phidgets_StepperPhidget_PHIDID_ANALOG_4OUTPUT 55L
#undef com_phidgets_StepperPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR
#define com_phidgets_StepperPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR 123L
#undef com_phidgets_StepperPhidget_PHIDID_BRIDGE_4INPUT
#define com_phidgets_StepperPhidget_PHIDID_BRIDGE_4INPUT 59L
#undef com_phidgets_StepperPhidget_PHIDID_ENCODER_1ENCODER_1INPUT
#define com_phidgets_StepperPhidget_PHIDID_ENCODER_1ENCODER_1INPUT 75L
#undef com_phidgets_StepperPhidget_PHIDID_ENCODER_HS_1ENCODER
#define com_phidgets_StepperPhidget_PHIDID_ENCODER_HS_1ENCODER 128L
#undef com_phidgets_StepperPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT
#define com_phidgets_StepperPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT 79L
#undef com_phidgets_StepperPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT
#define com_phidgets_StepperPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT 53L
#undef com_phidgets_StepperPhidget_PHIDID_GPS
#define com_phidgets_StepperPhidget_PHIDID_GPS 121L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_0_4
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_0_4 64L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_0_8
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_0_8 129L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_16_16
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_16_16 68L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_2_2_2
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_2_2_2 54L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_8_8_8
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_8_8_8 69L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD 125L
#undef com_phidgets_StepperPhidget_PHIDID_IR
#define com_phidgets_StepperPhidget_PHIDID_IR 77L
#undef com_phidgets_StepperPhidget_PHIDID_LED_64_ADV
#define com_phidgets_StepperPhidget_PHIDID_LED_64_ADV 76L
#undef com_phidgets_StepperPhidget_PHIDID_LINEAR_TOUCH
#define com_phidgets_StepperPhidget_PHIDID_LINEAR_TOUCH 118L
#undef com_phidgets_StepperPhidget_PHIDID_MOTORCONTROL_1MOTOR
#define com_phidgets_StepperPhidget_PHIDID_MOTORCONTROL_1MOTOR 62L
#undef com_phidgets_StepperPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR
#define com_phidgets_StepperPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR 89L
#undef com_phidgets_StepperPhidget_PHIDID_RFID_2OUTPUT
#define com_phidgets_StepperPhidget_PHIDID_RFID_2OUTPUT 49L
#undef com_phidgets_StepperPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE
#define com_phidgets_StepperPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE 52L
#undef com_phidgets_StepperPhidget_PHIDID_ROTARY_TOUCH
#define com_phidgets_StepperPhidget_PHIDID_ROTARY_TOUCH 119L
#undef com_phidgets_StepperPhidget_PHIDID_SPATIAL_ACCEL_3AXIS
#define com_phidgets_StepperPhidget_PHIDID_SPATIAL_ACCEL_3AXIS 127L
#undef com_phidgets_StepperPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS
#define com_phidgets_StepperPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS 51L
#undef com_phidgets_StepperPhidget_PHIDID_TEMPERATURESENSOR
#define com_phidgets_StepperPhidget_PHIDID_TEMPERATURESENSOR 112L
#undef com_phidgets_StepperPhidget_PHIDID_TEMPERATURESENSOR_4
#define com_phidgets_StepperPhidget_PHIDID_TEMPERATURESENSOR_4 50L
#undef com_phidgets_StepperPhidget_PHIDID_TEMPERATURESENSOR_IR
#define com_phidgets_StepperPhidget_PHIDID_TEMPERATURESENSOR_IR 60L
#undef com_phidgets_StepperPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8
#define com_phidgets_StepperPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8 381L
#undef com_phidgets_StepperPhidget_PHIDID_TEXTLCD_ADAPTER
#define com_phidgets_StepperPhidget_PHIDID_TEXTLCD_ADAPTER 61L
#undef com_phidgets_StepperPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR
#define com_phidgets_StepperPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR 122L
#undef com_phidgets_StepperPhidget_PHIDID_ACCELEROMETER_2AXIS
#define com_phidgets_StepperPhidget_PHIDID_ACCELEROMETER_2AXIS 113L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD 83L
#undef com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_4_8_8
#define com_phidgets_StepperPhidget_PHIDID_INTERFACEKIT_4_8_8 4L
#undef com_phidgets_StepperPhidget_PHIDID_LED_64
#define com_phidgets_StepperPhidget_PHIDID_LED_64 74L
#undef com_phidgets_StepperPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT
#define com_phidgets_StepperPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT 88L
#undef com_phidgets_StepperPhidget_PHIDID_PHSENSOR
#define com_phidgets_StepperPhidget_PHIDID_PHSENSOR 116L
#undef com_phidgets_StepperPhidget_PHIDID_RFID
#define com_phidgets_StepperPhidget_PHIDID_RFID 48L
#undef com_phidgets_StepperPhidget_PHIDID_SERVO_1MOTOR
#define com_phidgets_StepperPhidget_PHIDID_SERVO_1MOTOR 57L
#undef com_phidgets_StepperPhidget_PHIDID_SERVO_1MOTOR_OLD
#define com_phidgets_StepperPhidget_PHIDID_SERVO_1MOTOR_OLD 2L
#undef com_phidgets_StepperPhidget_PHIDID_SERVO_4MOTOR
#define com_phidgets_StepperPhidget_PHIDID_SERVO_4MOTOR 56L
#undef com_phidgets_StepperPhidget_PHIDID_SERVO_4MOTOR_OLD
#define com_phidgets_StepperPhidget_PHIDID_SERVO_4MOTOR_OLD 3L
#undef com_phidgets_StepperPhidget_PHIDID_TEXTLCD_2x20
#define com_phidgets_StepperPhidget_PHIDID_TEXTLCD_2x20 82L
#undef com_phidgets_StepperPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8
#define com_phidgets_StepperPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8 339L
#undef com_phidgets_StepperPhidget_PHIDID_TEXTLED_1x8
#define com_phidgets_StepperPhidget_PHIDID_TEXTLED_1x8 73L
#undef com_phidgets_StepperPhidget_PHIDID_TEXTLED_4x8
#define com_phidgets_StepperPhidget_PHIDID_TEXTLED_4x8 72L
#undef com_phidgets_StepperPhidget_PHIDID_WEIGHTSENSOR
#define com_phidgets_StepperPhidget_PHIDID_WEIGHTSENSOR 114L
#undef com_phidgets_StepperPhidget_PHIDCLASS_NOTHING
#define com_phidgets_StepperPhidget_PHIDCLASS_NOTHING 1L
#undef com_phidgets_StepperPhidget_PHIDCLASS_ACCELEROMETER
#define com_phidgets_StepperPhidget_PHIDCLASS_ACCELEROMETER 2L
#undef com_phidgets_StepperPhidget_PHIDCLASS_ADVANCEDSERVO
#define com_phidgets_StepperPhidget_PHIDCLASS_ADVANCEDSERVO 3L
#undef com_phidgets_StepperPhidget_PHIDCLASS_ANALOG
#define com_phidgets_StepperPhidget_PHIDCLASS_ANALOG 22L
#undef com_phidgets_StepperPhidget_PHIDCLASS_BRIDGE
#define com_phidgets_StepperPhidget_PHIDCLASS_BRIDGE 23L
#undef com_phidgets_StepperPhidget_PHIDCLASS_ENCODER
#define com_phidgets_StepperPhidget_PHIDCLASS_ENCODER 4L
#undef com_phidgets_StepperPhidget_PHIDCLASS_FREQUENCYCOUNTER
#define com_phidgets_StepperPhidget_PHIDCLASS_FREQUENCYCOUNTER 21L
#undef com_phidgets_StepperPhidget_PHIDCLASS_GPS
#define com_phidgets_StepperPhidget_PHIDCLASS_GPS 5L
#undef com_phidgets_StepperPhidget_PHIDCLASS_INTERFACEKIT
#define com_phidgets_StepperPhidget_PHIDCLASS_INTERFACEKIT 7L
#undef com_phidgets_StepperPhidget_PHIDCLASS_LED
#define com_phidgets_StepperPhidget_PHIDCLASS_LED 8L
#undef com_phidgets_StepperPhidget_PHIDCLASS_MOTORCONTROL
#define com_phidgets_StepperPhidget_PHIDCLASS_MOTORCONTROL 9L
#undef com_phidgets_StepperPhidget_PHIDCLASS_PHSENSOR
#define com_phidgets_StepperPhidget_PHIDCLASS_PHSENSOR 10L
#undef com_phidgets_StepperPhidget_PHIDCLASS_RFID
#define com_phidgets_StepperPhidget_PHIDCLASS_RFID 11L
#undef com_phidgets_StepperPhidget_PHIDCLASS_SERVO
#define com_phidgets_StepperPhidget_PHIDCLASS_SERVO 12L
#undef com_phidgets_StepperPhidget_PHIDCLASS_STEPPER
#define com_phidgets_StepperPhidget_PHIDCLASS_STEPPER 13L
#undef com_phidgets_StepperPhidget_PHIDCLASS_TEMPERATURESENSOR
#define com_phidgets_StepperPhidget_PHIDCLASS_TEMPERATURESENSOR 14L
#undef com_phidgets_StepperPhidget_PHIDCLASS_TEXTLCD
#define com_phidgets_StepperPhidget_PHIDCLASS_TEXTLCD 15L
#undef com_phidgets_StepperPhidget_PHIDCLASS_TEXTLED
#define com_phidgets_StepperPhidget_PHIDCLASS_TEXTLED 16L
#undef com_phidgets_StepperPhidget_PHIDCLASS_WEIGHTSENSOR
#define com_phidgets_StepperPhidget_PHIDCLASS_WEIGHTSENSOR 17L
/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getMotorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_StepperPhidget_getMotorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getInputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_StepperPhidget_getInputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getInputState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_StepperPhidget_getInputState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getAcceleration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getAcceleration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getAccelerationMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getAccelerationMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getAccelerationMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getAccelerationMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setAcceleration
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setAcceleration
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocity
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocityMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocityMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocityMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocityMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setVelocityLimit
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setVelocityLimit
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocityLimit
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocityLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getPositionMax
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getPositionMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getPositionMin
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getPositionMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setCurrentPosition
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setCurrentPosition
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentPosition
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getCurrentPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setTargetPosition
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setTargetPosition
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getTargetPosition
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getTargetPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentLimit
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrentLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setCurrentLimit
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setCurrentLimit
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrentMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrentMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setEngaged
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setEngaged
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getEngaged
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_StepperPhidget_getEngaged
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getStopped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_StepperPhidget_getStopped
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableStepperPositionChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableStepperPositionChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableStepperVelocityChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableStepperVelocityChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableCurrentChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableCurrentChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableInputChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableInputChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
