/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_Dictionary */

#ifndef _Included_com_phidgets_Dictionary
#define _Included_com_phidgets_Dictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phidgets_Dictionary
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_Dictionary_create
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    nativeDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_nativeDelete
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    nativeOpenRemote
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_nativeOpenRemote
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    nativeOpenRemoteIP
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_nativeOpenRemoteIP
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    nativeAddKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_nativeAddKey
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    nativeRemoveKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_nativeRemoveKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    nativeGetKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_phidgets_Dictionary_nativeGetKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    getServerAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_phidgets_Dictionary_getServerAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    getServerID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_phidgets_Dictionary_getServerID
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    getServerPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_Dictionary_getServerPort
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    isAttached
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_Dictionary_isAttached
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    isAttachedToServer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_Dictionary_isAttachedToServer
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    enableServerConnectEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_enableServerConnectEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_Dictionary
 * Method:    enableServerDisconnectEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_Dictionary_enableServerDisconnectEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
