/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_LEDPhidget */

#ifndef _Included_com_phidgets_LEDPhidget
#define _Included_com_phidgets_LEDPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_LEDPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_LEDPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_LEDPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_LEDPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_INFO
#define com_phidgets_LEDPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_LEDPhidget_PHIDGET_LOG_VERBOSE 6L
#undef com_phidgets_LEDPhidget_PHIDID_NOTHING
#define com_phidgets_LEDPhidget_PHIDID_NOTHING 1L
#undef com_phidgets_LEDPhidget_PHIDID_ACCELEROMETER_3AXIS
#define com_phidgets_LEDPhidget_PHIDID_ACCELEROMETER_3AXIS 126L
#undef com_phidgets_LEDPhidget_PHIDID_ADVANCEDSERVO_1MOTOR
#define com_phidgets_LEDPhidget_PHIDID_ADVANCEDSERVO_1MOTOR 130L
#undef com_phidgets_LEDPhidget_PHIDID_ADVANCEDSERVO_8MOTOR
#define com_phidgets_LEDPhidget_PHIDID_ADVANCEDSERVO_8MOTOR 58L
#undef com_phidgets_LEDPhidget_PHIDID_ANALOG_4OUTPUT
#define com_phidgets_LEDPhidget_PHIDID_ANALOG_4OUTPUT 55L
#undef com_phidgets_LEDPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR
#define com_phidgets_LEDPhidget_PHIDID_BIPOLAR_STEPPER_1MOTOR 123L
#undef com_phidgets_LEDPhidget_PHIDID_BRIDGE_4INPUT
#define com_phidgets_LEDPhidget_PHIDID_BRIDGE_4INPUT 59L
#undef com_phidgets_LEDPhidget_PHIDID_ENCODER_1ENCODER_1INPUT
#define com_phidgets_LEDPhidget_PHIDID_ENCODER_1ENCODER_1INPUT 75L
#undef com_phidgets_LEDPhidget_PHIDID_ENCODER_HS_1ENCODER
#define com_phidgets_LEDPhidget_PHIDID_ENCODER_HS_1ENCODER 128L
#undef com_phidgets_LEDPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT
#define com_phidgets_LEDPhidget_PHIDID_ENCODER_HS_4ENCODER_4INPUT 79L
#undef com_phidgets_LEDPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT
#define com_phidgets_LEDPhidget_PHIDID_FREQUENCYCOUNTER_2INPUT 53L
#undef com_phidgets_LEDPhidget_PHIDID_GPS
#define com_phidgets_LEDPhidget_PHIDID_GPS 121L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_0_4
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_0_4 64L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_0_8
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_0_8 129L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_16_16
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_16_16 68L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_2_2_2
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_2_2_2 54L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_8_8_8
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_8_8_8 69L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_8_8_8_w_LCD 125L
#undef com_phidgets_LEDPhidget_PHIDID_IR
#define com_phidgets_LEDPhidget_PHIDID_IR 77L
#undef com_phidgets_LEDPhidget_PHIDID_LED_64_ADV
#define com_phidgets_LEDPhidget_PHIDID_LED_64_ADV 76L
#undef com_phidgets_LEDPhidget_PHIDID_LINEAR_TOUCH
#define com_phidgets_LEDPhidget_PHIDID_LINEAR_TOUCH 118L
#undef com_phidgets_LEDPhidget_PHIDID_MOTORCONTROL_1MOTOR
#define com_phidgets_LEDPhidget_PHIDID_MOTORCONTROL_1MOTOR 62L
#undef com_phidgets_LEDPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR
#define com_phidgets_LEDPhidget_PHIDID_MOTORCONTROL_HC_2MOTOR 89L
#undef com_phidgets_LEDPhidget_PHIDID_RFID_2OUTPUT
#define com_phidgets_LEDPhidget_PHIDID_RFID_2OUTPUT 49L
#undef com_phidgets_LEDPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE
#define com_phidgets_LEDPhidget_PHIDID_RFID_2OUTPUT_READ_WRITE 52L
#undef com_phidgets_LEDPhidget_PHIDID_ROTARY_TOUCH
#define com_phidgets_LEDPhidget_PHIDID_ROTARY_TOUCH 119L
#undef com_phidgets_LEDPhidget_PHIDID_SPATIAL_ACCEL_3AXIS
#define com_phidgets_LEDPhidget_PHIDID_SPATIAL_ACCEL_3AXIS 127L
#undef com_phidgets_LEDPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS
#define com_phidgets_LEDPhidget_PHIDID_SPATIAL_ACCEL_GYRO_COMPASS 51L
#undef com_phidgets_LEDPhidget_PHIDID_TEMPERATURESENSOR
#define com_phidgets_LEDPhidget_PHIDID_TEMPERATURESENSOR 112L
#undef com_phidgets_LEDPhidget_PHIDID_TEMPERATURESENSOR_4
#define com_phidgets_LEDPhidget_PHIDID_TEMPERATURESENSOR_4 50L
#undef com_phidgets_LEDPhidget_PHIDID_TEMPERATURESENSOR_IR
#define com_phidgets_LEDPhidget_PHIDID_TEMPERATURESENSOR_IR 60L
#undef com_phidgets_LEDPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8
#define com_phidgets_LEDPhidget_PHIDID_TEXTLCD_2x20_w_8_8_8 381L
#undef com_phidgets_LEDPhidget_PHIDID_TEXTLCD_ADAPTER
#define com_phidgets_LEDPhidget_PHIDID_TEXTLCD_ADAPTER 61L
#undef com_phidgets_LEDPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR
#define com_phidgets_LEDPhidget_PHIDID_UNIPOLAR_STEPPER_4MOTOR 122L
#undef com_phidgets_LEDPhidget_PHIDID_ACCELEROMETER_2AXIS
#define com_phidgets_LEDPhidget_PHIDID_ACCELEROMETER_2AXIS 113L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_0_8_8_w_LCD 83L
#undef com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_4_8_8
#define com_phidgets_LEDPhidget_PHIDID_INTERFACEKIT_4_8_8 4L
#undef com_phidgets_LEDPhidget_PHIDID_LED_64
#define com_phidgets_LEDPhidget_PHIDID_LED_64 74L
#undef com_phidgets_LEDPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT
#define com_phidgets_LEDPhidget_PHIDID_MOTORCONTROL_LV_2MOTOR_4INPUT 88L
#undef com_phidgets_LEDPhidget_PHIDID_PHSENSOR
#define com_phidgets_LEDPhidget_PHIDID_PHSENSOR 116L
#undef com_phidgets_LEDPhidget_PHIDID_RFID
#define com_phidgets_LEDPhidget_PHIDID_RFID 48L
#undef com_phidgets_LEDPhidget_PHIDID_SERVO_1MOTOR
#define com_phidgets_LEDPhidget_PHIDID_SERVO_1MOTOR 57L
#undef com_phidgets_LEDPhidget_PHIDID_SERVO_1MOTOR_OLD
#define com_phidgets_LEDPhidget_PHIDID_SERVO_1MOTOR_OLD 2L
#undef com_phidgets_LEDPhidget_PHIDID_SERVO_4MOTOR
#define com_phidgets_LEDPhidget_PHIDID_SERVO_4MOTOR 56L
#undef com_phidgets_LEDPhidget_PHIDID_SERVO_4MOTOR_OLD
#define com_phidgets_LEDPhidget_PHIDID_SERVO_4MOTOR_OLD 3L
#undef com_phidgets_LEDPhidget_PHIDID_TEXTLCD_2x20
#define com_phidgets_LEDPhidget_PHIDID_TEXTLCD_2x20 82L
#undef com_phidgets_LEDPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8
#define com_phidgets_LEDPhidget_PHIDID_TEXTLCD_2x20_w_0_8_8 339L
#undef com_phidgets_LEDPhidget_PHIDID_TEXTLED_1x8
#define com_phidgets_LEDPhidget_PHIDID_TEXTLED_1x8 73L
#undef com_phidgets_LEDPhidget_PHIDID_TEXTLED_4x8
#define com_phidgets_LEDPhidget_PHIDID_TEXTLED_4x8 72L
#undef com_phidgets_LEDPhidget_PHIDID_WEIGHTSENSOR
#define com_phidgets_LEDPhidget_PHIDID_WEIGHTSENSOR 114L
#undef com_phidgets_LEDPhidget_PHIDCLASS_NOTHING
#define com_phidgets_LEDPhidget_PHIDCLASS_NOTHING 1L
#undef com_phidgets_LEDPhidget_PHIDCLASS_ACCELEROMETER
#define com_phidgets_LEDPhidget_PHIDCLASS_ACCELEROMETER 2L
#undef com_phidgets_LEDPhidget_PHIDCLASS_ADVANCEDSERVO
#define com_phidgets_LEDPhidget_PHIDCLASS_ADVANCEDSERVO 3L
#undef com_phidgets_LEDPhidget_PHIDCLASS_ANALOG
#define com_phidgets_LEDPhidget_PHIDCLASS_ANALOG 22L
#undef com_phidgets_LEDPhidget_PHIDCLASS_BRIDGE
#define com_phidgets_LEDPhidget_PHIDCLASS_BRIDGE 23L
#undef com_phidgets_LEDPhidget_PHIDCLASS_ENCODER
#define com_phidgets_LEDPhidget_PHIDCLASS_ENCODER 4L
#undef com_phidgets_LEDPhidget_PHIDCLASS_FREQUENCYCOUNTER
#define com_phidgets_LEDPhidget_PHIDCLASS_FREQUENCYCOUNTER 21L
#undef com_phidgets_LEDPhidget_PHIDCLASS_GPS
#define com_phidgets_LEDPhidget_PHIDCLASS_GPS 5L
#undef com_phidgets_LEDPhidget_PHIDCLASS_INTERFACEKIT
#define com_phidgets_LEDPhidget_PHIDCLASS_INTERFACEKIT 7L
#undef com_phidgets_LEDPhidget_PHIDCLASS_LED
#define com_phidgets_LEDPhidget_PHIDCLASS_LED 8L
#undef com_phidgets_LEDPhidget_PHIDCLASS_MOTORCONTROL
#define com_phidgets_LEDPhidget_PHIDCLASS_MOTORCONTROL 9L
#undef com_phidgets_LEDPhidget_PHIDCLASS_PHSENSOR
#define com_phidgets_LEDPhidget_PHIDCLASS_PHSENSOR 10L
#undef com_phidgets_LEDPhidget_PHIDCLASS_RFID
#define com_phidgets_LEDPhidget_PHIDCLASS_RFID 11L
#undef com_phidgets_LEDPhidget_PHIDCLASS_SERVO
#define com_phidgets_LEDPhidget_PHIDCLASS_SERVO 12L
#undef com_phidgets_LEDPhidget_PHIDCLASS_STEPPER
#define com_phidgets_LEDPhidget_PHIDCLASS_STEPPER 13L
#undef com_phidgets_LEDPhidget_PHIDCLASS_TEMPERATURESENSOR
#define com_phidgets_LEDPhidget_PHIDCLASS_TEMPERATURESENSOR 14L
#undef com_phidgets_LEDPhidget_PHIDCLASS_TEXTLCD
#define com_phidgets_LEDPhidget_PHIDCLASS_TEXTLCD 15L
#undef com_phidgets_LEDPhidget_PHIDCLASS_TEXTLED
#define com_phidgets_LEDPhidget_PHIDCLASS_TEXTLED 16L
#undef com_phidgets_LEDPhidget_PHIDCLASS_WEIGHTSENSOR
#define com_phidgets_LEDPhidget_PHIDCLASS_WEIGHTSENSOR 17L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_20mA
#define com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_20mA 1L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_40mA
#define com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_40mA 2L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_60mA
#define com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_60mA 3L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_80mA
#define com_phidgets_LEDPhidget_PHIDGET_LED_CURRENT_LIMIT_80mA 4L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_1_7V
#define com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_1_7V 1L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_2_75V
#define com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_2_75V 2L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_3_9V
#define com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_3_9V 3L
#undef com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_5_0V
#define com_phidgets_LEDPhidget_PHIDGET_LED_VOLTAGE_5_0V 4L
/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_LEDPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getCurrentLimit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_LEDPhidget_getCurrentLimit__
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    setCurrentLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_LEDPhidget_setCurrentLimit__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getVoltage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_LEDPhidget_getVoltage
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    setVoltage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_LEDPhidget_setVoltage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getLEDCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_LEDPhidget_getLEDCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getDiscreteLED
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_LEDPhidget_getDiscreteLED
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    setDiscreteLED
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_LEDPhidget_setDiscreteLED
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getBrightness
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_LEDPhidget_getBrightness
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    setBrightness
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_LEDPhidget_setBrightness
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getCurrentLimit
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_LEDPhidget_getCurrentLimit__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    setCurrentLimit
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_LEDPhidget_setCurrentLimit__ID
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
